# Generated by Django 4.1.4 on 2022-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImg', models.CharField(max_length=255, verbose_name='Путь до картинки')),
                ('productType', models.CharField(max_length=255, verbose_name='Тип товара')),
                ('productTitle', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('productBrand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImg', models.CharField(max_length=255, verbose_name='Путь до картинки')),
                ('productType', models.CharField(max_length=255, verbose_name='Тип товара')),
                ('productTitle', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('productBrand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImg', models.CharField(max_length=255, verbose_name='Путь до картинки')),
                ('productType', models.CharField(max_length=255, verbose_name='Тип товара')),
                ('productTitle', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('productBrand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('userLastname', models.CharField(max_length=255, verbose_name='Фамилия клиента')),
                ('userPhone', models.CharField(max_length=255, verbose_name='Телефон клиента')),
                ('userEmail', models.CharField(max_length=255, verbose_name='Почта клиента')),
                ('userLogin', models.CharField(max_length=255, verbose_name='Логин клиента')),
                ('userPassword', models.CharField(max_length=255, verbose_name='Пароль клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerName', models.CharField(max_length=255, verbose_name='Имя работника')),
                ('workerLastname', models.CharField(max_length=255, verbose_name='Фамилия работника')),
                ('workerPhone', models.CharField(max_length=255, verbose_name='Телефон работника')),
                ('workerEmail', models.CharField(max_length=255, verbose_name='Почта работника')),
                ('workerPos', models.CharField(max_length=255, verbose_name='Должность работника')),
                ('workerSalary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата')),
            ],
        ),
    ]
