# Generated by Django 4.1.3 on 2022-12-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sneakers', '0002_alter_product_productprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
