# Generated by Django 4.1.5 on 2023-01-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sneakers', '0004_remove_bought_productbrand_remove_bought_productimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought',
            name='productPrice',
        ),
    ]
