# Generated by Django 4.1.5 on 2023-01-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sneakers', '0005_remove_bought_productprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
